trigger:
  - master

resources:
  - repo: self

variables:
  # Go
  GOVERSION: '1.13'
  GOROOT: '/usr/local/go$(GOVERSION)'
  GOPATH: '/home/vsts/go'
  GOBIN: '$(GOPATH)/bin'

jobs:
  - job: build
    displayName: Build stkcli
    pool:
      vmImage: ubuntu-18.04
    steps:
      # Set up go environment
      - bash: |
          set -e

          # Add to GOBIN to PATH
          echo '##vso[task.prependpath]$(GOBIN)'
          echo '##vso[task.prependpath]$(GOROOT)/bin'
        displayName: "Set up go environment"
      # Build Linux amd64
      - bash: |
          set -e

          BUILD_ID=$(Build.BuildNumber)
          BUILD_TIME=$(date -u +'%Y-%m-%dT%H:%M:%S')
          COMMIT_HASH=$(git log --pretty=format:'%h' -n 1)

          GO111MODULE=on \
            go build \
              -ldflags "-X github.com/ItalyPaleAle/stkcli/buildinfo.ENV=production -X github.com/ItalyPaleAle/stkcli/buildinfo.BuildID=$BUILD_ID -X github.com/ItalyPaleAle/stkcli/buildinfo.BuildTime=$BUILD_TIME -X github.com/ItalyPaleAle/stkcli/buildinfo.CommitHash=$COMMIT_HASH" \
              -o bin/stkcli_linux_amd64
        displayName: "Build Linux amd64"
      # Build Linux arm64
      - bash: |
          set -e

          BUILD_ID=$(Build.BuildNumber)
          BUILD_TIME=$(date -u +'%Y-%m-%dT%H:%M:%S')
          COMMIT_HASH=$(git log --pretty=format:'%h' -n 1)

          GO111MODULE=on \
          GOOS=linux \
          GOARCH=arm64 \
            go build \
              -ldflags "-X github.com/ItalyPaleAle/stkcli/buildinfo.ENV=production -X github.com/ItalyPaleAle/stkcli/buildinfo.BuildID=$BUILD_ID -X github.com/ItalyPaleAle/stkcli/buildinfo.BuildTime=$BUILD_TIME -X github.com/ItalyPaleAle/stkcli/buildinfo.CommitHash=$COMMIT_HASH" \
              -o bin/stkcli_linux_arm64
        displayName: "Build Linux arm64"
      # Build Linux armhf
      - bash: |
          set -e

          BUILD_ID=$(Build.BuildNumber)
          BUILD_TIME=$(date -u +'%Y-%m-%dT%H:%M:%S')
          COMMIT_HASH=$(git log --pretty=format:'%h' -n 1)

          GO111MODULE=on \
          GOOS=linux \
          GOARCH=arm \
          GOARM=7 \
            go build \
              -ldflags "-X github.com/ItalyPaleAle/stkcli/buildinfo.ENV=production -X github.com/ItalyPaleAle/stkcli/buildinfo.BuildID=$BUILD_ID -X github.com/ItalyPaleAle/stkcli/buildinfo.BuildTime=$BUILD_TIME -X github.com/ItalyPaleAle/stkcli/buildinfo.CommitHash=$COMMIT_HASH" \
              -o bin/stkcli_linux_armhf
        displayName: "Build Linux armhf"
      # Build macOS
      - bash: |
          set -e

          BUILD_ID=$(Build.BuildNumber)
          BUILD_TIME=$(date -u +'%Y-%m-%dT%H:%M:%S')
          COMMIT_HASH=$(git log --pretty=format:'%h' -n 1)

          GO111MODULE=on \
          GOOS=darwin \
          GOARCH=amd64 \
            go build \
              -ldflags "-X github.com/ItalyPaleAle/stkcli/buildinfo.ENV=production -X github.com/ItalyPaleAle/stkcli/buildinfo.BuildID=$BUILD_ID -X github.com/ItalyPaleAle/stkcli/buildinfo.BuildTime=$BUILD_TIME -X github.com/ItalyPaleAle/stkcli/buildinfo.CommitHash=$COMMIT_HASH" \
              -o bin/stkcli_macos
        displayName: "Build macOS"
      # Build Windows 64-bit
      - bash: |
          set -e

          BUILD_ID=$(Build.BuildNumber)
          BUILD_TIME=$(date -u +'%Y-%m-%dT%H:%M:%S')
          COMMIT_HASH=$(git log --pretty=format:'%h' -n 1)

          GO111MODULE=on \
          GOOS=windows \
          GOARCH=amd64 \
            go build \
              -ldflags "-X github.com/ItalyPaleAle/stkcli/buildinfo.ENV=production -X github.com/ItalyPaleAle/stkcli/buildinfo.BuildID=$BUILD_ID -X github.com/ItalyPaleAle/stkcli/buildinfo.BuildTime=$BUILD_TIME -X github.com/ItalyPaleAle/stkcli/buildinfo.CommitHash=$COMMIT_HASH" \
              -o bin/stkcli_win64.exe
        displayName: "Build Windows 64-bit"
      # Build Windows 32-bit
      - bash: |
          set -e

          BUILD_ID=$(Build.BuildNumber)
          BUILD_TIME=$(date -u +'%Y-%m-%dT%H:%M:%S')
          COMMIT_HASH=$(git log --pretty=format:'%h' -n 1)

          GO111MODULE=on \
          GOOS=windows \
          GOARCH=386 \
            go build \
              -ldflags "-X github.com/ItalyPaleAle/stkcli/buildinfo.ENV=production -X github.com/ItalyPaleAle/stkcli/buildinfo.BuildID=$BUILD_ID -X github.com/ItalyPaleAle/stkcli/buildinfo.BuildTime=$BUILD_TIME -X github.com/ItalyPaleAle/stkcli/buildinfo.CommitHash=$COMMIT_HASH" \
              -o bin/stkcli_win32.exe
        displayName: "Build Windows 32-bit"
      # Copy binaries to the artifacts staging directory
      - task: CopyFiles@2
        displayName: Copy binaries to the artifacts staging directory
        inputs:
          sourceFolder: 'bin/'
          contents: '**/*'
          targetFolder: '$(Build.ArtifactStagingDirectory)'
      # Publish binaries as artifacts
      - task: PublishBuildArtifacts@1
        displayName: 'Publish build artifacts'
        inputs:
          artifactName: drop
