trigger:
  - master

resources:
  - repo: self

variables:
  # Go
  GOVERSION: '1.13'
  GOROOT: '/usr/local/go$(GOVERSION)'
  GOPATH: '/home/vsts/go'

jobs:
  - job: build
    displayName: Build artifacts for Linux (amd64, arm64, armhf)
    pool:
      vmImage: ubuntu-18.04
    steps:
      # Set up go environment
      - bash: |
          set -e

          # Add to GOBIN to PATH
          echo '##vso[task.prependpath]$(GOBIN)'
          echo '##vso[task.prependpath]$(GOROOT)/bin'
        displayName: "Set up go environment"
      # Build amd64
      - bash: |
          set -e

          GO111MODULE=on \
            go build \
              -o bin/smplatform_linux_amd64
        displayName: "Build amd64"
      # Build arm64
      - bash: |
          set -e

          GO111MODULE=on \
          GOOS=linux \
          GOARCH=arm64 \
            go build \
              -o bin/smplatform_linux_arm64
        displayName: "Build arm64"
      # Build armhf
      - bash: |
          set -e

          GO111MODULE=on \
          GOOS=linux \
          GOARCH=arm \
          GOARM=7 \
            go build \
              -o bin/smplatform_linux_armhf
        displayName: "Build armhf"
      # Copy binaries to the artifacts staging directory
      - task: CopyFiles@2
        displayName: Copy binaries to the artifacts staging directory
        inputs:
          sourceFolder: 'bin/'
          contents: '**/*'
          targetFolder: '$(Build.ArtifactStagingDirectory)'
      # Publish binaries as artifacts
      - task: PublishBuildArtifacts@1
        displayName: 'Publish build artifacts'
        inputs:
          artifactName: drop
